name: atommovr_env
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy
  - scikit-learn
  - xarray
  - ipykernel
  - matplotlib
  - scikit-image
  - seaborn
  - opencv
  - scipy
  - setuptools # needed because lazy-build calls PPSU/setupc.py
  - pip
  - pip:
      - -e .[dev]
      - imageio==2.36.1
      - pillow==11.1.0